# 1 - Load Baltimore's PD Arrest Data

```{r}
library(readr, warn.conflicts = FALSE) # CSV file I/O, e.g. the read_csv function
library(leaflet, warn.conflicts = FALSE) # interactive map
library(dplyr, warn.conflicts = FALSE) # data manipulation for map
```

```{r}
# Input data files are available in the "../input/" directory.
system("ls ../input") 
```


```{r}
# load data from Baltimore's Police Arrest Dataset
data <- read_csv('../input/BPD_Arrests.csv')
```

# 2 - Clean & Transform Data
```{r}
# get a subset of the data for the information considered important
crimeSet = data[,c("Age", "Race", "ArrestDate", "ChargeDescription","IncidentLocation", "Location 1")]
# lets change the name of the last column
colnames(crimeSet) <- c("Age", "Race", "ArrestDate", "ChargeDescription","IncidentLocation", "Location")
```

```{r}
# clean where data is NA
crimeSet[crimeSet==""] <- NA
crimeSet = na.omit(crimeSet)
```

```{r}
# remove parenthesis and white spaces from location column (lat, lon)
crimeSet$Location <- gsub("[\\(|\\)]","",as.character( crimeSet$Location))
crimeSet$Location <- gsub(" ","",as.character( crimeSet$Location))
```

```{r}
# split Location into lon and lat columns
splitdat = do.call("rbind", strsplit(crimeSet$Location, ","))
splitdat = data.frame(apply(splitdat, 2, as.character))
names(splitdat) = paste("loc", 1:2, sep = "")
crimeSet$lat = splitdat$loc1 
crimeSet$lon = splitdat$loc2 
```

# 3 - Build Map with Leaflet and add arrest data
```{r}
# center map at -76.617543, 39.293767 which is a place in downtown Baltimore
m <- leaflet() %>%
  addTiles() %>%  
  setView(-76.617543, 39.293767, zoom = 12)

# in each marker, add a popup with important information
m %>%
  addCircles (data=crimeSet, 
              lat= ~lat,
              lng = ~lon, 
              popup=paste(crimeSet$ArrestDate, 
                          " | Age: ", crimeSet$Age,
                          " | Race: ", crimeSet$Race, 
                          " | Carge", crimeSet$ChargeDescription, 
                          " | Location: ", crimeSet$IncidentLocation), 
              weight = 0.4, 
              color="#8B1A1A", 
              stroke = TRUE, 
              fillOpacity = 0.6)
```